name: 编译 Android 正式版 APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v6

      - name: 安装 .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: 安装 JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: 安装 Android 工作负载
        run: dotnet workload restore GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj

      - name: 还原依赖
        run: dotnet restore --configfile GalaxyBudsClient/nuget.config GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj

      - name: 编译 Android 正式版 APK
        run: >-
          dotnet publish GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj
          -c Release
          -f net10.0-android36.1
          -p:NoDemo=true
          -p:AndroidPackageFormats=apk
          -p:BuildInParallel=false
          -m:1
          -o artifacts
          --no-restore

      - name: 上传签名 APK
        uses: actions/upload-artifact@v6
        with:
          name: GalaxyBudsClient-android
          path: |
            artifacts/**/*-Signed.apk
          if-no-files-found: warn