    - name: Publish Android APK
      run: |
        dotnet publish GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj \
        -c Release \
        -f net10.0-android36.1 \
        -p:AndroidPackageFormats=apk \
        -p:AndroidCreatePackage=true \
        -p:AndroidSdkDirectory=$ANDROID_HOME \
        --no-restore \
        -maxcpucount:1

    - name: Upload APK artifact
      uses: actions/upload-artifact@v6
      with:
        name: GalaxyBudsClient_Android_APK
        path: GalaxyBudsClient.Android/bin/Release/net10.0-android36.1/apk/*.apk
