name: Compile Android APK

on:
  push:
    branches: [ master, NET10 ]
  pull_request:
    branches: [ master ]
  release:
     types: 
       - published
       - prereleased
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
       
    - name: Install Android Workload
      run: dotnet workload install android

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Restore dependencies
      run: |
        dotnet restore \
        --configfile GalaxyBudsClient/nuget.config \
        GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj

    - name: Publish Android APK
      run: |
        dotnet publish GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj \
        -c Release \
        -f net10.0-android36.1 \
        -p:AndroidPackageFormats=apk \
        -p:AndroidSdkDirectory=$ANDROID_HOME \
        --no-restore

    - name: Upload APK artifact
      uses: actions/upload-artifact@v6
      with:
        name: GalaxyBudsClient_Android_APK
        path: GalaxyBudsClient.Android/bin/Release/net10.0-android36.1/apk/*.apk

  attach-to-release:
    runs-on: ubuntu-latest
    needs: [build-android]
    if: github.event_name == 'release'
    
    steps:
    - name: Download Android APK artifact
      uses: actions/download-artifact@v7
      with:
        name: GalaxyBudsClient_Android_APK

    - name: Rename APK
      run: mv ./*.apk GalaxyBudsClient_Android_Universal.apk

    - uses: AButler/upload-release-assets@v3.0.1
      with:
        files: '*.apk'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
