name: Compile Android APK

on:
  push:
    branches: [ master, NET10 ]
  pull_request:
    branches: [ master ]
  release:
     types: 
       - published
       - prereleased
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      MSBUILDSINGLEPROCESS: true
    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
       
    - name: Install Android Workload
      run: dotnet workload install android

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # 密钥恢复（如果你启用签名，保留；不需要签名可整块删除）
    - name: Restore Keystore
      env:
        KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      run: |
        echo "$KEYSTORE_B64" | base64 -d > app.keystore

    - name: Restore dependencies
      run: |
        dotnet restore \
        --configfile GalaxyBudsClient/nuget.config \
        GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj
        
    - name: Publish Android APK
      env:
        KEY_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
        KEY_STORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        KEY_PASS: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: |
        dotnet publish GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj \
        -c Release \
        -f net10.0-android36.1 \
        -p:AndroidPackageFormats=apk \
        -p:AndroidCreatePackage=true \
        -p:AndroidSdkDirectory=$ANDROID_HOME \
        -p:AndroidSigningKeyStore=app.keystore \
        -p:AndroidSigningKeyAlias=$KEY_ALIAS \
        -p:AndroidSigningKeyPass=$KEY_PASS \
        -p:AndroidSigningStorePass=$KEY_STORE_PASS \
        -o ./build_output \
        --no-restore \
        -maxcpucount:1

    - name: Rename APK
      run: |
        mv ./build_output/*.apk GalaxyBudsClient_Android_Universal_Signed.apk

    # 只在release触发时上传资产，无artifact中转！！
    - name: Upload APK to Release
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v3.0.1
      with:
        files: 'GalaxyBudsClient_Android_Universal_Signed.apk'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    # 可选：保留artifact用于调试（注意：下载依旧是zip，仅作测试使用，不用于发布）
    - name: Debug Artifact(可选)
      uses: actions/upload-artifact@v6
      with:
        name: APK_Debug
        path: GalaxyBudsClient_Android_Universal_Signed.apk
